### PR TITLE
Added Stats js to render performance charts

### PR DESCRIPTION
**Pull request by NPatel10**
## Summary

Stats JS graphs are added in Debug panel in location. Some UI changes are implemented to make panel look good.

Note - In firefox memory panel will not work since firefox does not support `performance.memory`.

## References

- [x] #5856 

## Checklist
- [ ] CI/CD checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Typescript passing via `npm run check-errors`
  - [ ] Unit & Integration tests passing via `npm run test`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Reviewers

@HexaField

### CODE REVIEW

**Comment by HexaField** [comment]
Screenshot from 2022-05-03 14-38-13
Screenshot from 2022-05-03 14-37-20

looking great!!! only thing is if we can tweak the CSS such that the 4 buttons dont go onto 2 lines if the scrollbar is visible. and lets move the tick and reset buttons to the top, above the 4 buttons

**Comment by NPatel10** [comment]
> looking great!!! only thing is if we can tweak the CSS such that the 4 buttons dont go onto 2 lines if the scrollbar is visible. and lets move the tick and reset buttons to the top, above the 4 buttons

Made some changes to address this.

**Comment by HexaField** [comment]
Screenshot from 2022-05-05 18-54-57
looking great, lets just move the reset & tick up the top to be aligned to the right of the helper buttons, will save space and look a bit better

**Comment by NPatel10** [comment]
> looking great, lets just move the reset & tick up the top to be aligned to the right of the helper buttons, will save space and look a bit better

Implemented this.

**Review by HexaField — APPROVED** [review]

**Pull request merged**
