### PR TITLE
Changes to clean user menu css

### PR DESCRIPTION
**Pull request by hanzlamateen**
## Summary

Changes to clean user menu scss

## References

#7216

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Review by mrhegemon — APPROVED** [review]
Great work. We will need another pass o. UX soon, but this allows us to restart our design process.

**Comment by speigg** [comment]
I get this error in the console when opening the Share menu 

```validateDOMNesting(...): <h6> cannot appear as a child of <h2>. [...] ```

**Review by speigg — CHANGES_REQUESTED** [review]
I get this error in the console when opening the Share menu 

```validateDOMNesting(...): <h6> cannot appear as a child of <h2>. [...] ```

**Comment by hanzlamateen** [comment]
> I get this error in the console when opening the Share menu

@speigg I am unable to see any such error on my end.

image

**Review by speigg — APPROVED** [review]

**Pull request merged**
