### PR TITLE
all translation supported by azure

### PR DESCRIPTION
**Pull request by johnfelipe**

### CODE REVIEW

**Comment by johnfelipe** [comment]
only missing in client-core this one:
sk sl sm so sq sr-Cyrl sr-Latn sv sw ta te th ti tk tlh-Latn tlh-Piqd to tr tt ty ug uk ur uz vi yua yue zh-Hans zh-Hant zu
ill do it in 24 hours

**Comment by HexaField** [comment]
Please rebase and solve conflicts

**Comment by HexaField** [comment]
Please also include a script that runs the auto-generator.

**Comment by johnfelipe** [comment]
conflict resolve

**Comment by johnfelipe** [comment]
Bro i will do it but without azure credentials, ok?

**Comment by HexaField** [comment]
moving this PR to https://github.com/XRFoundation/XREngine-i18n

**Pull request closed without merging**
