### PR TITLE
Fix server w/ ClientStorage.ts

### PR DESCRIPTION
**Pull request by speigg**
Importing ImmortalDB dynamically to avoid errors on the server.

### CODE REVIEW

**Review by shawticus — COMMENTED** [review]
I patched this with a dynamic import on ClientStorage itself-- if we import this it will still work with no conflicts. However-- is there a use case where we want client storage on a client that doesn't have a window object? (Could a Node.js instance ever be the client?)

**Comment by speigg** [comment]
So we should probably just check for the existence of the `window` object?

**Comment by speigg** [comment]
We do this kind of check elsewhere throughout the codebase. This should be sufficient: ```js
const isBrowserCheck = typeof window === 'object' && typeof document !== 'undefined'
```

**Comment by shawticus** [comment]
@

**Pull request closed without merging**
