### PR TITLE
added scroll option and improved instance chat UI

### PR DESCRIPTION
**Pull request by FabriceIRANKUNDA**
## Summary
_A summary of changes being made in this PR_
Refactor Instance Chat UI
Added scrolling messages
Screen Shot 2022-04-28 at 11 36 09
Screen Shot 2022-04-28 at 12 56 53

## References

closes #_insert number here_

## Checklist
- [ ] CI/CD checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Typescript passing via `npm run check-errors`
  - [ ] Unit & Integration tests passing via `npm run test`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] If this PR is still a WIP, convert to a draft 
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Reviewers

_Reviewers for this PR_

### CODE REVIEW

**Comment by HexaField** [comment]
Screenshot from 2022-05-02 20-08-47
- lets add a 50% transparent black background to make it easier to see what you type, and somehow align it with the button
- text box should wrap and make the area bigger on a new line when approaching the edge
- previous messages should populate just above the text area, rather than from the top of the text history area (messages should be bottom aligned rather than top aligned)
- previous message area should not clip into the above section, if it does, it is partially hidden under the avatar thumbnails

**Comment by HexaField** [comment]
Screenshot from 2022-05-03 16-20-38
Screenshot from 2022-05-03 16-24-50
Screenshot from 2022-05-03 16-26-15


- let's remove the horizontal scroll, it is unnecessary.
- the entire chat area needs to be in front of the other UI as well, and for mobile, lets extend this transparent black background to include the entire text area for readability over the other UI elements
- the chat area on mobile should take up 2/3 the screen, from the bottom, such that just the top of the scene is fully visible. clicking outside of the text area should then close the chat area.
- on desktop, lets move the 'exit chat' button to be to the left of the chat rather than the right, and on mobile move it to above the screen as to not waste horizontal space
- on both desktop and mobile, the previous messages should move upwards and not fall behind the text area (see second and third image)

**Comment by speigg** [comment]
XREngine  Home

This is still quite messy and cluttered on mobile; can you clean this up? Can we fade out other UI elements while chat is open?

**Review by HexaField — CHANGES_REQUESTED** [review]
- ```World Chat...``` when the chat box is empty has an offset where it is a few pixels lower than when text is entered.

- minimising chat will have the chat button come up from the bottom of the screen as it does with the layout hide/show button, instead it should transition from where the close chat button is in the expanded view

- cannot click showhide button to hide top media items once they have been minimised and reopened

-

**Pull request merged**
