### PR TITLE
Nayan   small bug fixes

### PR DESCRIPTION
**Pull request by NPatel10**
## Summary

Worked on following issues,
- [x] #6279 
- [x] #6290 - worked on Editor services
- [x] #6306 

## Checklist
- [x] If this PR is still a WIP, convert to a draft 
- [x] When this PR is ready, mark it as "Ready for review"
- [x] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewers

@HexaField @speigg

### CODE REVIEW

**Review by HexaField — CHANGES_REQUESTED** [review]
this is not following the style guide set out in [this PR](https://github.com/XRFoundation/XREngine/pull/6123/files) for hyperflux actions, state & receptors. please ensure it is following the exact format show in the linked PR

**Comment by HexaField** [comment]
seeing an error immediately upon loading Screenshot from 2022-06-08 21-31-26

**Comment by HexaField** [comment]
changing renderer lighting mode (unlit, lit, shadows etc) requires a reload to take effect

**Comment by HexaField** [comment]
selecting more than one object crashes
Screenshot from 2022-06-08 21-38-12

**Comment by HexaField** [comment]
various errors and crash when quit button is clicked 

Screenshot from 2022-06-08 21-40-13

**Comment by NPatel10** [comment]
> 

Not able to recreate this issue.

**Comment by NPatel10** [comment]
> selecting more than one object crashes

Not able to recreate

**Comment by NPatel10** [comment]
> * [ ]  changing scenes will sometimes fail

Not able to recreate. If you can provide screen shot of the issue maybe I can identify the cause.

**Comment by NPatel10** [comment]
There is one general observation on `getComponent` function. This component returns null sometimes and there is no type check for this. This is the main reason for above errors and errors which is not identified yet. What should we do about this issue? let me know your thoughts.

**Pull request merged**
