### PR TITLE
Uploaded files in editor will have lower case extension.

### LINKED ISSUE #6419: [Bug]: Editor file import is case sensitive
PR to be reviewed by @barankyle and @hanzlamateen - Kyle and Hanzla, please message him when this branch is ready for review.

File importing from desktop at least is case sensitive.  If a file extension is lowercase (e.g. .png) the upload is successful.  If the file extension is uppercase (e.g. .PNG) the upload is unsuccessful.  File import should be case insensitive.

### PR DESCRIPTION
**Pull request by hanzlamateen**
## Summary

This PR fixes case sensitive file import issue in editor drag and drop mechanism.

## References

closes #6419

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Review by HexaField — CHANGES_REQUESTED** [review]
lets also make lower case in the api server when a file is uploaded

**Comment by hanzlamateen** [comment]
> lets also make lower case in the api server when a file is uploaded

Updated the code. Kindly review

**Comment by barankyle** [comment]
It seems like all .glbs aren't being handled properly, even ones with lowercase extensions are being parsed as folders.

**Comment by hanzlamateen** [comment]
> It seems like all .glbs aren't being handled properly, even ones with lowercase extensions are being parsed as folders.

Can you let me know which ones are having issues? I tried Cyberbot and it worked fine. Also, is the issue referred on this branch only or on dev as well?

**Review by HexaField — APPROVED** [review]

**Pull request merged**
