### PR TITLE
Refactor Media 

### LINKED ISSUE #7642: Refactor MediaStreams

### PR DESCRIPTION
**Pull request by HexaField**
## Summary

- [x] Refactor MediaStreams into Hyperflux
- [x] Remove duplicated media toggle functions
- [x] Separate user media window state from UI 
- [ ] Improve naming of (or merge) MediaStreams.ts and MediaStreamService.ts

## References

closes #7642

## Checklist
- [x] If this PR is still a WIP, convert to a draft
- [x] When this PR is ready, mark it as "Ready for review"
- [x] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [x] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Review by barankyle — APPROVED** [review]
Looks great and all of the permutations of muting from both ends worked, which is one reason the logic is a bit messier than one would think (e.g. I mute your audio, then you turn off your audio, then you turn it back on, and I still have you muted). There's a few console.log's that should be removed before merging.

**Review by speigg — COMMENTED** [review]
Looks like `receiveJoinMediaServer` is not being used anywhere? Is this for future use?

**Comment by HexaField** [comment]
> Looks like receiveJoinMediaServer is not being used anywhere? Is this for future use?

It is being used

**Comment by speigg** [comment]
@HexaField  ah, my bad, GitHub was hiding that diff because it was a large diff.

**Review by speigg — APPROVED** [review]

**Pull request merged**
