### PR TITLE
use s.merge rather than directly updating states

### PR DESCRIPTION
**Pull request by zulqarnainhanif**

### CODE REVIEW

**Review by NateTheGreatt — APPROVED** [review]

**Review by NateTheGreatt — CHANGES_REQUESTED** [review]
looks like there were some merge issues:
```
Error:  packages/client-core/src/admin/services/Setting/AdminRedisSettingService.ts: SyntaxError: Merge conflict marker encountered. (22:1)
Error:    20 |     switch (action.type) {
Error:    21 |       case 'ADMIN_REDIS_SETTING_FETCHED':
Error:  > 22 | <<<<<<< HEAD
Error:       | ^
Error:    23 |         result = action.adminRedisSettingResult
Error:    24 |         return s.merge({
Error:    25 |           redisSettings: {
Error:  packages/client-core/src/admin/services/Setting/AuthSettingService.ts: SyntaxError: Merge conflict marker encountered. (25:1)
Error:    23 |     switch (action.type) {
Error:    24 |       case 'ADMIN_AUTH_SETTING_FETCHED':
Error:  > 25 | <<<<<<< HEAD
Error:       | ^
Error:    26 |         result = action.adminRedisSettingResult
Error:    27 |         return s.merge({
Error:    28 |           authSettings: {
Error:  packages/client-core/src/admin/services/Setting/AwsSettingService.ts: SyntaxError: Merge conflict marker encountered. (23:1)
Error:    21 |     switch (action.type) {
Error:    22 |       case 'ADMIN_AWS_SETTING_FETCHED':
Error:  > 23 | <<<<<<< HEAD
Error:       | ^
Error:    24 |         result = action.adminRedisSettingResult
Error:    25 |         return s.merge({ awsSettings: { awsSettings: result.data, updateNeeded: false } })
Error:    26 | =======
```
and more: https://github.com/XRFoundation/XREngine/runs/4092426243?check_suite_focus=true

**Comment by zulqarnainhanif** [comment]
@NateTheGreatt and @HexaField sorry about that, pushed a fix please have a look now.

**Comment by NateTheGreatt** [comment]
thanks @zulqarnainhanif. almost there! just a few lint issues left
```
 Error:  packages/client-core/src/social/services/FriendService.ts: SyntaxError: ',' expected. (86:22)
Error:    84 |             friends: {
Error:    85 |               ...s.friends.value,
Error:  > 86 |               friends[patchedFriendIndex]: otherUser,
Error:       |                      ^
Error:    87 |             },
Error:    88 |           })
Error:    89 |         }
Error:  packages/client-core/src/social/services/GroupService.ts: SyntaxError: ',' expected. (114:21)
Error:    112 |             groups: {
Error:    113 |               ...s.groups.value,
Error:  > 114 |               groups[groupIndex]: updateGroup
Error:        |                     ^
Error:    115 |             }
Error:    116 |           })
Error:    117 |         }
[warn] packages/client-core/src/social/services/LocationService.ts
[warn] packages/client-core/src/social/services/PartyService.ts
[warn] packages/client-core/src/social/services/WebxrNativeService.ts
[warn] packages/client-core/src/user/services/AuthService.ts
Error:  packages/client-core/src/user/services/UserService.ts: SyntaxError: ',' expected. (45:23)
Error:    43 |         } else {
Error:    44 |           return s.merge({
Error:  > 45 |             layerUsers[idx]: newUser,
Error:       |                       ^
Error:    46 |             layerUsersUpdateNeeded: true
Error:    47 |           })
Error:    48 |         }
[warn] packages/social/src/state/TheFeedsBookmarkState.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
Error: Process completed with exit code 2.
```

**Comment by zulqarnainhanif** [comment]
@NateTheGreatt i had discussion about those with @HexaField he said it would be okay to leave them for now. @kimenyikevin  and he will go over everything to fix such things later.

**Comment by HexaField** [comment]
This has a lot of problems and it seems like you incorrectly merged dev and overrid all the changes i made to the admin services. I'm going to close this.

**Pull request closed without merging**
