### PR TITLE
Working NPX dev config and install.

### PR DESCRIPTION
**Pull request by jerknose**
## Summary

_A summary of changes being made in this PR_

Hey guys. I created a working prototype of a npx installer. Once published, we'll have a single command to configure everything.

"npx @xrengine/xrengine folder_name"

Then just run "cd folder_name & npm run dev"

Also, there's a GitHub action to auto publish to npm: https://github.com/marketplace/actions/npm-publish

## References

closes #_insert number here_

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

To test locally:
Run 'npm i -g'
Run 'npx xrengine folder_name'

### CODE REVIEW

**Review by HexaField — APPROVED** [review]
Nice!

**Review by speigg — CHANGES_REQUESTED** [review]
We're in the process of moving everything over from xrengine -> etherealengine namespaces; let's do that here preemptively. 

We have an `@etherealengine` org for npm, perhaps we should do `npx @etherealengine/install` for this?

**Comment by jerknose** [comment]
> We're in the process of moving everything over from xrengine -> etherealengine namespaces; let's do that here preemptively.
> 
> We have an `@etherealengine` org for npm, perhaps we should do `npx @etherealengine/install` for this?

The default npx behavior is to use @org_name/repo_name. But I believe we can define multiple scripts in Package.json.

i.e. npx @org_name/repo_name script_name var_1

So, something like this (with the current repo name)

@etherealengine/xrengine install my_engine_folder

**Comment by speigg** [comment]
> The default npx behavior is to use @org_name/repo_name

@jerknose  Can you point me to some documentation about this?

**Comment by jerknose** [comment]
@speigg

NPX Tutorial: https://dev.to/9zemian5/basic-npx-command-line-tool-45k4
NPX Docs: https://docs.npmjs.com/cli/v9/commands/npx?v=true
NPM Publish Docs: https://docs.npmjs.com/cli/v9/commands/npm-publish?v=true
NPM Publish Action: https://github.com/marketplace/actions/npm-publish

**Comment by speigg** [comment]
Not seeing any reason we can't do `npx @etherealengine/install` for this; just waiting on npm support to get back to me about the @etherealengine org, which is being name-squatted right now...

**Comment by jerknose** [comment]
@speigg Can we merge this in as a working template? I think which org name, and repo name are a separate issue.

**Review by speigg — APPROVED** [review]

**Pull request merged**
