### PR TITLE
mappa#7: add dampening to avatar speed to prevent circling

### PR DESCRIPTION
**Pull request by patreeceeo**
## Summary

The autopilot system, in addition to directing the avatar to the most recently clicked point, also simulates its momentum. If the player clicks on a point that's slightly off of the avatar's current path, the path curves. Sometimes if the curvature is tight and momentum great enough, the avatar will start orbiting the point it's trying to get to.

This PR ensures that some dampening is always applied so that when the avatar starts orbiting, it will eventually loose enough momentum to "fall" to within the allowable distance from the target point.

Before:

https://user-images.githubusercontent.com/578371/141836332-893bfd87-6cc3-4fd8-a16c-316dcf4514d2.mp4

After:

The circling behavior can maybe still happen, but you'd have to really try to make it happen and wouldn't last as long when it does happen.

https://user-images.githubusercontent.com/578371/141868788-d0882395-420d-4df3-8720-dda17b3848b5.mp4

## Checklist

- [ ] Pre-push checks pass `npm run check`
  - [ ] Linter passing via `npm run lint`
  - [ ] Unit & Integration tests passing via `npm run test:packages`
  - [ ] Docker build process passing via `npm run build-client`
- [ ] Changes have been manually QA'd 
- [ ] Changes reviewed by at least 2 approved reviewers

## References

References to pertaining issue(s)
[mappa#7](https://github.com/lagunalabsio/mappa/issues/7)

## Reviewers

@HexaField @speigg @NateTheGreatt

### CODE REVIEW

**Comment by shawwwwwwww** [comment]
@hanzlamateen please review and pass it along to @apolancojr who will merge when it's reviewed.

**Comment by patreeceeo** [comment]
Also, wanted to mention that there could be a more elegant solution given a way to set the avatar's velocity directly as a vector rather than using acceleration via a simulated joystick. I tried to figure out how to achieve that myself but was too unfamiliar with that code, which seems complex.

**Comment by speigg** [comment]
Just based on your video, something still feels off about the character movement. Not sure what is going on there.

**Comment by patreeceeo** [comment]
If you mean how the avatar doesn't always face the direction it's moving, that was an issue before these changes.

**Review by hanzlamateen — APPROVED** [review]
Looks good. Over to @apolancojr

**Comment by apolancojr** [comment]
@patreeceeo @hanzlamateen please merge the latest changes from the base branch into this branch to prevent possible conflicts before I accept this PR.

**Comment by hanzlamateen** [comment]
> @patreeceeo @hanzlamateen please merge the latest changes from the base branch into this branch to prevent possible conflicts before I accept this PR.

@apolancojr done

**Comment by patreeceeo** [comment]
Is this ready to merge?

**Comment by patreeceeo** [comment]
Need another reviewer, according to the PR template.

**Pull request merged**
