### PR TITLE
implemented Hookstate in auth

### PR DESCRIPTION
**Pull request by kinjalravel**

### CODE REVIEW

**Comment by speigg** [comment]
This looks perfect, great job!

**Review by speigg — APPROVED** [review]

**Review by NateTheGreatt — CHANGES_REQUESTED** [review]
great work @kinjalravel! there are still authentication errors occurring when i run this branch locally tho. could you merge `dev` and fix the conflicts / auth errors?

**Comment by NateTheGreatt** [comment]
there still seems to be some issues, but i think we're almost there @kinjalravel!

i'm seeing an infinite stream of `null` values being logged to the console that aren't being logged in `dev` when run locally:
```
[dev-server] [0] Trace: null
[dev-server] [0]     at Location.location_hooks_default.before.find (/home/nate/Code/XREngine/packages/server-core/src/social/location/location.hooks.ts:34:17)
[dev-server] [0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev-server] [0] Trace: null
[dev-server] [0]     at Location.location_hooks_default.before.find (/home/nate/Code/XREngine/packages/server-core/src/social/location/location.hooks.ts:34:17)
[dev-server] [0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev-server] [0] Trace: null
[dev-server] [0]     at Location.location_hooks_default.before.find (/home/nate/Code/XREngine/packages/server-core/src/social/location/location.hooks.ts:34:17)
[dev-server] [0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[dev-server] [0] Trace: null
[dev-server] [0]     at Location.location_hooks_default.before.find (/home/nate/Code/XREngine/packages/server-core/src/social/location/location.hooks.ts:34:17)
[dev-server] [0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

as shown by the trace, the `service('location').find` hook is being called over and over again indefinitely for some reason. any ideas on what might be doing that?

**Comment by kinjalravel** [comment]
@speigg @NateTheGreatt Can you guys merge this ASAP

**Pull request merged**
