### PR TITLE
[fix] RigidBodyComponent type errors

### PR DESCRIPTION
**Pull request by patreeceeo**
## Summary

Was running in to some type errors with the latest code.

## References

closes #_insert number here_

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] [ensure all checks pass](https://github.com/XRFoundation/XREngine/wiki/Testing-&-Contributing)
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Comment by HexaField** [comment]
Can you share what errors you're getting?

**Comment by patreeceeo** [comment]
The compiler thought that the return value of `getComponent` was `true`, the default for the first type argument to `defineComponent`. Is that type supposed to be inferred somehow from the schema?

**Comment by HexaField** [comment]
I'm not able to reproduce this. Is this in a project? Can you share your tsconfig.json ?

**Comment by patreeceeo** [comment]
Sorry just seeing this. Here's my tsconfig:

```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": [
      "esnext",
      "dom",
      "dom.iterable"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "module": "CommonJS",
    "strict": false,
    "strictNullChecks": true,
    "strictBindCallApply": true,
    "noImplicitAny": false,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "jsx": "react",
    "isolatedModules": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "outDir": "./lib"
  },
  "exclude": [
    "../projects/projects/**",
    "**/node_modules/**"
  ],
  "include": [
    "./**/*.ts",
    "./**/*.tsx"
  ]
}
```

**Comment by patreeceeo** [comment]
This could be a gap in my understanding of typescript, but the default value for the component data type (first type parameter to defineComponent) is `true`, so wouldn't we need to override wherever that's not the case?

**Comment by patreeceeo** [comment]
But yes, the typeerror is happening in a project. And I'm pointing my package.json entries directly at my local filesystem development clone of XRE.

**Pull request closed without merging**
