### PR TITLE
Added a view to show location not found

### PR DESCRIPTION
**Pull request by zulqarnainhanif**
## Summary

add a screen that tells the user to check his location

## Checklist
- [x] Pre-push checks pass `npm run check`
  - [x] Linter passing via `npm run lint`
  - [x] Unit & Integration tests passing via `npm run test:packages`
  - [x] Docker build process passing via `npm run build-client`
- [x] Changes have been manually QA'd 
- [ ] Changes reviewed by at least 2 approved reviewers

## References

https://github.com/XRFoundation/XREngine/issues/3874

## Reviewers

@HexaField

### CODE REVIEW

**Comment by barankyle** [comment]
I'd made a warning modal trigger that's supposed to do this already: https://github.com/XRFoundation/XREngine/blob/dev/packages/client/src/components/World/GameServerWarnings.tsx#L62

I'm not sure why it's not triggering, since it runs off the same state value. I'm not sure we need the new things in this PR if we could make the modal work again.

**Review by HexaField — CHANGES_REQUESTED** [review]
Kyle's comment is correct, we should be re-using the modal we already have for this.

**Comment by zulqarnainhanif** [comment]
@HexaField @barankyle update the warning component to stay there when value for noCountDown is true and remove my changes.

**Review by HexaField — APPROVED** [review]
Seems to work now, thanks.

**Review by barankyle — APPROVED** [review]

**Pull request merged**
